apiVersion: apps/v1
kind: Deployment
metadata:
  name: galeana-api
  namespace: galeana-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: galeana-api
  template:
    metadata:
      labels:
        app: galeana-api
    spec:
      containers:
        - name: galeana-api
          image: galeana-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
