name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ejecutar pruebas
        run: ./mvnw test

      - name: Construir proyecto
        run: ./mvnw clean package

      - name: Instalar Snyk
        run: npm install -g snyk

      - name: Autenticarse en Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Escaneo de seguridad
        run: snyk test
